from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class GenerateRequest(BaseModel):
    apiKey: str
    prompt: str

@app.post("/api/code")
async def generate_code(request: GenerateRequest):
    # Placeholder: Simulate LLM response with dummy code
    dummy_code = {
        "html": f"<html><body><h1>{request.prompt}</h1></body></html>",
        "css": "h1 { color: green; text-align: center; }",
        "js": "console.log('Generated by code-gen');"
    }
    return {"code": dummy_code}